spring:
  config:
    import: optional:application-secret.yaml

  application:
    name: jpa

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ai1018-prod-backend-db.ctvyzknz7zxl.ap-southeast-1.rds.amazonaws.com:3306/library?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

jwt:
  secret: ${JWT_SECRET}
  # Access Token 만료 시간 (2시간 = 2 * 60 * 60 * 1000ms)
  access-expiration: 7200000
  # Refresh Token 만료 시간 (2주 = 14 * 24 * 60 * 60 * 1000ms)
  refresh-expiration: 1209600000

# external:
#   api-key: ${EXTERNAL_API_KEY}


app:
  base-url: http://54.255.204.194
  s3:
    bucket: user045-book
    region: ap-southeast-1
    prefix: bookcovers/
    return-mode: PUBLIC_URL
    public-base-url: https://user045-book.s3.ap-southeast-1.amazonaws.com
